services:
  app:
    container_name: dev-todo-frontend
    image: dev-todo-frontend
    build: 
      context: .
      dockerfile: dev.dockerfile
    ports:
      - 5173:5173
    environment:
      VITE_BACKEND_URL: http://127.0.0.1:3000/
    volumes:
      - ./:/usr/src/app
      - frontDeps:/usr/src/app/node_modules
    # stdin_open: true
    # tty: true
    # command: ['']
volumes:
  frontDeps:
    name: frontDeps
