services:
  nginx:
    container_name: reverse-proxy-server
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
  app:
    container_name: app
    image: my-app-frontend
    depends_on:
      - server
  server:
    container_name: server
    image: my-app-backend
    environment:
      BACKEND_URI: "mongodb://root:password@mongo:27017/Persons"
      URI: "mongodb://root:password@mongo:27017/Persons"
    volumes:
      - backendDeps:/usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    container_name: mongo-server
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: Persons
    volumes:
      - ./BackEnd/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - myAppMongoData:/data/db
      - myAppMongoConfigData:/data/configdb
      
volumes:
  frontendDeps:
    name: frontendDeps
  backendDeps:
    name: backendDeps
  myAppMongoData:
    name: myAppMongoData
  myAppMongoConfigData:
    name: myAppMongoConfigData