services:
  mongo:
    image: mongo
    ports:
      - 3001:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    # extra_hosts:
    #   - myhost:host-gateway
  redis:
    image: redis:7.2.7
    ports:
      - 3002:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redisData:/data
    # extra_hosts:
    #   - myhost:host-gateway
volumes:
  redisData: