services:
  mongo:
    container_name: mongo-server
    image: mongo
    ports:
      - 3001:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongoData:/data/db
      - mongoConfigData:/data/configdb
  redis:
    container_name: redis-server
    image: redis
    ports:
      - 3002:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redisData:/data
  app:
    container_name: dev-todo-backend
    image: dev-todo-backend
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://root:password@mongo:27017/the_database
      REDIS_URL: redis://redis:6379
    volumes:
      - ./:/usr/src/app
      - backDeps:/usr/src/app/node_modules
    depends_on:
      - mongo
      - redis
    # extra_hosts:
    #   - myhost:host-gateway
volumes:
  redisData:
    name: redisData
  mongoData:
    name: mongoData
  mongoConfigData:
    name: mongoConfigData
  backDeps:
    name: backDeps
